# Status left
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=default,fg=#{@thm_red},bold]  #S },#{#[bg=default,fg=#{@thm_green}]  #S }}"
set -ga status-left "#[bg=default,fg=#{@thm_overlay_0}]"
set -ga status-left "#[bg=default,fg=#{@thm_red}]  #{pane_current_command} "
set -ga status-left "#[bg=default,fg=#{@thm_overlay_0}]"
set -ga status-left "#[bg=default,fg=#{@thm_blue}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "
set -ga status-left "#[bg=default,fg=#{@thm_overlay_0}]#{?window_zoomed_flag,│,}"
set -ga status-left "#[bg=default,fg=#{@thm_yellow}]#{?window_zoomed_flag,  zoom ,}"

# Status right
set -g status-right-length 100
set -g status-right ""
set -ga status-right "#[bg=default,fg=#{@thm_green}] 󰭦 %Y/%m/%d 󰅐 %I:%M %p "

# Status bar
set -g status-position top
set -g status-style "bg=default,fg=#{@thm_fg}"
set -g status-justify "absolute-centre"

# Pane borders
setw -g pane-border-status top
setw -g pane-border-format ""
setw -g pane-active-border-style "bg=default,fg=#{@thm_overlay_2}"
setw -g pane-border-style "bg=default,fg=#{@thm_surface_2}"
setw -g pane-border-lines single

# Window titles
set -wg automatic-rename on
set -g automatic-rename-format "Window"

set -g window-status-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-style "bg=default,fg=#{@thm_rosewater}"
set -g window-status-last-style "bg=default,fg=#{@thm_overlay_0}"
set -g window-status-activity-style "bg=default,fg=#{@thm_red}"
set -g window-status-bell-style "bg=default,fg=#{@thm_red},bold"
set -gF window-status-separator "#[bg=default,fg=#{@thm_overlay_0}]"
set -g window-status-current-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-current-style "bg=default,fg=#{@thm_green},bold"

