# Main tmux entry point
source-file "$HOME/.config/tmux/core.conf"
source-file "$HOME/.config/tmux/keybinds.tmux"
source-file "$HOME/.config/tmux/plugins.conf"
source-file "$HOME/.config/tmux/theme.conf"
source-file "$HOME/.config/tmux/status.conf"

run-shell "#{HOME}/.local/share/tmux/plugins/catppuccin/tmux/catppuccin.tmux"
