# Core behavior

set -g mouse on
setw -g mode-keys vi
set -sg escape-time 10
set -g focus-events on

# Reload everything
unbind r
bind r source-file ~/.tmux.conf \; display-message "tmux reloaded"

# Pane nav
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
