# Plugins

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

# bootstrap TPM
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm && $HOME/.tmux/plugins/tpm/bin/install_plugins'"
run '$HOME/.tmux/plugins/tpm/tpm'
