# Main tmux entry point

# Always use absolute paths (important)
set -g @dotfiles_tmux_dir "$HOME/dotfiles/config/tmux"

source-file "$HOME/dotfiles/config/tmux/core.conf"
source-file "$HOME/dotfiles/config/tmux/plugins.conf"
source-file "$HOME/dotfiles/config/tmux/theme.conf"
source-file "$HOME/dotfiles/config/tmux/status.conf"

run-shell "#{HOME}/.local/share/tmux/plugins/catppuccin/tmux/catppuccin.tmux"
