# Main tmux entry point

# Keep paths portable (works even if repo isn't ~/dotfiles)
set -g @dotfiles_tmux_dir "$HOME/.config/tmux"

source-file "#{@dotfiles_tmux_dir}/core.conf"
source-file "#{@dotfiles_tmux_dir}/plugins.conf"
source-file "#{@dotfiles_tmux_dir}/theme.conf"
source-file "#{@dotfiles_tmux_dir}/status.conf"

run-shell "#{HOME}/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux"
